### ISSUE TITLE
Enhancement: 관리자 헤더 로그인(로그아웃) 아이콘 &  페이지 검색 버튼 추가 요쳥

### ISSUE THREAD

**Issue by ByeongminLee** [Team-Stuckyi/TheGreatCatsby-Publishing#19]
# 관리자 공통 부분 추가 요청

![요청](https://user-images.githubusercontent.com/71276006/149517475-50b9fc43-ca01-4d81-98be-db5c4aafab2c.png)
 
1. 관리자 헤더 로그인(로그아웃) 아이콘
2. 페이지 검색 버튼 추가 요쳥

**Comment by x3r0s** [comment]
https://github.com/Team-Stuckyi/TheGreatCatsby-Publishing/commit/d3636da663a77980618b6ec2f310501a24e3824f

수정 완료하였습니다.
